const state = {
  stream: null,
  imageBlob: null,
  imageDataURL: null,
  ocrText: '',
  lang: 'ara',
  uiLang: 'ara',
  worker: null,
  tesseractReady: false
};

const $ = id => document.getElementById(id);

const I18N = {
  ara: {
    dir: 'rtl',
    ocrLang: 'ara',
    appTitle: 'إسكان',
    tagline: 'ماسح المستندات الذكي',
    placeholder: 'اضغطي "فتح الكاميرا" لبدء المسح',
    btnOpenCamera: 'فتح الكاميرا',
    btnCapture: 'التقاط',
    btnRetake: 'إعادة',
    btnOcr: 'استخراج النص',
    btnUpload: 'رفع صورة',
    btnExportPdf: 'تصدير PDF',
    btnExportTxt: 'تصدير نص',
    resultPlaceholder: 'سيظهر النص المستخرج هنا…',
    statusCameraReady: 'الكاميرا جاهزة — وجهيها نحو المستند',
    statusImageCaptured: 'تم التقاط الصورة. اضغطي على "استخراج النص"',
    statusImageUploaded: 'تم تحميل الصورة. اضغطي على "استخراج النص"',
    statusOcrSuccess: n => `تم بنجاح — تم استخراج ${n} حرفاً`,
    statusNoText: '(لم يتم اكتشاف أي نص)',
    statusCameraError: e => 'تعذر فتح الكاميرا: ' + (e || 'تحققي من الصلاحيات'),
    statusTesseractError: 'فشل في تحميل محرك التعرف على النصوص. تأكدي من الاتصال بالإنترنت.',
    statusOcrError: e => 'فشل استخراج النص: ' + (e || ''),
    statusPdfGenerating: 'جارٍ إنشاء ملف PDF…',
    statusPdfSuccess: 'تم تحميل ملف PDF بنجاح',
    statusPdfError: e => 'فشل إنشاء PDF: ' + (e || ''),
    statusTxtSuccess: 'تم تحميل ملف TXT بنجاح',
    loaderTesseract: 'جارٍ تحميل محرك التعرف على النصوص… قد يستغرق بضع ثوانٍ',
    loaderLang: 'جارٍ إعداد محرك اللغة…',
    loaderOcr: 'جارٍ استخراج النص من الصورة…',
    loaderPdf: 'جارٍ إنشاء ملف PDF…',
    loaderProcessing: (p, s) => `معالجة النص: ${Math.round(p * 100)}% — ${s || ''}`
  },
  eng: {
    dir: 'ltr',
    ocrLang: 'eng',
    appTitle: 'Iskaan',
    tagline: 'Smart Document Scanner',
    placeholder: 'Tap "Open Camera" to start scanning',
    btnOpenCamera: 'Open Camera',
    btnCapture: 'Capture',
    btnRetake: 'Retake',
    btnOcr: 'Extract Text',
    btnUpload: 'Upload Image',
    btnExportPdf: 'Export PDF',
    btnExportTxt: 'Export Text',
    resultPlaceholder: 'Extracted text will appear here…',
    statusCameraReady: 'Camera ready — point it at the document',
    statusImageCaptured: 'Image captured. Tap "Extract Text"',
    statusImageUploaded: 'Image uploaded. Tap "Extract Text"',
    statusOcrSuccess: n => `Success — extracted ${n} characters`,
    statusNoText: '(No text detected)',
    statusCameraError: e => 'Cannot open camera: ' + (e || 'check permissions'),
    statusTesseractError: 'Failed to load text recognition engine. Check your internet connection.',
    statusOcrError: e => 'Text extraction failed: ' + (e || ''),
    statusPdfGenerating: 'Generating PDF…',
    statusPdfSuccess: 'PDF file downloaded successfully',
    statusPdfError: e => 'PDF creation failed: ' + (e || ''),
    statusTxtSuccess: 'TXT file downloaded successfully',
    loaderTesseract: 'Loading text recognition engine… may take a few seconds',
    loaderLang: 'Setting up language engine…',
    loaderOcr: 'Extracting text from image…',
    loaderPdf: 'Generating PDF…',
    loaderProcessing: (p, s) => `Processing text: ${Math.round(p * 100)}% — ${s || ''}`
  },
  fra: {
    dir: 'ltr',
    ocrLang: 'fra',
    appTitle: 'Iskaan',
    tagline: 'Scanner de Documents Intelligent',
    placeholder: 'Appuyez sur « Ouvrir Caméra » pour commencer',
    btnOpenCamera: 'Ouvrir Caméra',
    btnCapture: 'Capturer',
    btnRetake: 'Reprendre',
    btnOcr: 'Extraire le Texte',
    btnUpload: 'Télécharger Image',
    btnExportPdf: 'Exporter PDF',
    btnExportTxt: 'Exporter Texte',
    resultPlaceholder: 'Le texte extrait apparaîtra ici…',
    statusCameraReady: 'Caméra prête — pointez-la vers le document',
    statusImageCaptured: 'Image capturée. Appuyez sur « Extraire Texte »',
    statusImageUploaded: 'Image téléchargée. Appuyez sur « Extraire Texte »',
    statusOcrSuccess: n => `Succès — ${n} caractères extraits`,
    statusNoText: '(Aucun texte détecté)',
    statusCameraError: e => 'Impossible d\'ouvrir la caméra : ' + (e || 'vérifiez les autorisations'),
    statusTesseractError: 'Échec du chargement du moteur de reconnaissance. Vérifiez votre connexion.',
    statusOcrError: e => 'Échec de l\'extraction du texte : ' + (e || ''),
    statusPdfGenerating: 'Génération du PDF…',
    statusPdfSuccess: 'Fichier PDF téléchargé avec succès',
    statusPdfError: e => 'Échec de la création du PDF : ' + (e || ''),
    statusTxtSuccess: 'Fichier TXT téléchargé avec succès',
    loaderTesseract: 'Chargement du moteur de reconnaissance… peut prendre quelques secondes',
    loaderLang: 'Configuration du moteur de langue…',
    loaderOcr: 'Extraction du texte de l\'image…',
    loaderPdf: 'Génération du PDF…',
    loaderProcessing: (p, s) => `Traitement du texte : ${Math.round(p * 100)}% — ${s || ''}`
  },
  engara: {
    dir: 'ltr',
    ocrLang: 'eng+ara',
    appTitle: 'Iskaan',
    tagline: 'Smart Document Scanner — ماسح المستندات الذكي',
    placeholder: 'Tap "Open Camera" to start scanning',
    btnOpenCamera: 'Open Camera',
    btnCapture: 'Capture',
    btnRetake: 'Retake',
    btnOcr: 'Extract Text',
    btnUpload: 'Upload Image',
    btnExportPdf: 'Export PDF',
    btnExportTxt: 'Export Text',
    resultPlaceholder: 'Extracted text will appear here…',
    statusCameraReady: 'Camera ready — point it at the document',
    statusImageCaptured: 'Image captured. Tap "Extract Text"',
    statusImageUploaded: 'Image uploaded. Tap "Extract Text"',
    statusOcrSuccess: n => `Success — extracted ${n} characters`,
    statusNoText: '(No text detected)',
    statusCameraError: e => 'Cannot open camera: ' + (e || 'check permissions'),
    statusTesseractError: 'Failed to load text recognition engine. Check your internet connection.',
    statusOcrError: e => 'Text extraction failed: ' + (e || ''),
    statusPdfGenerating: 'Generating PDF…',
    statusPdfSuccess: 'PDF file downloaded successfully',
    statusPdfError: e => 'PDF creation failed: ' + (e || ''),
    statusTxtSuccess: 'TXT file downloaded successfully',
    loaderTesseract: 'Loading text recognition engine… may take a few seconds',
    loaderLang: 'Setting up language engine…',
    loaderOcr: 'Extracting text from image…',
    loaderPdf: 'Generating PDF…',
    loaderProcessing: (p, s) => `Processing text: ${Math.round(p * 100)}% — ${s || ''}`
  }
};
